### Homework Week1

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

np.__version__

'1.22.4'

#### Question 1: NumPy version is 1.22.4

In [3]:
df = pd.read_csv('data.csv', sep=',')
df.head(5)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

In [5]:
df.describe()

Year    Engine HP  Engine Cylinders  Number of Doors  \
count  11914.000000  11845.00000      11884.000000     11908.000000   
mean    2010.384338    249.38607          5.628829         3.436093   
std        7.579740    109.19187          1.780559         0.881315   
min     1990.000000     55.00000          0.000000         2.000000   
25%     2007.000000    170.00000          4.000000         2.000000   
50%     2015.000000    227.00000          6.000000         4.000000   
75%     2016.000000    300.00000          6.000000         4.000000   
max     2017.000000   1001.00000         16.000000         4.000000   

        highway MPG      city mpg    Popularity          MSRP  
count  11914.000000  11914.000000  11914.000000  1.191400e+04  
mean      26.637485     19.733255   1554.911197  4.059474e+04  
std        8.863001      8.987798   1441.855347  6.010910e+04  
min       12.000000      7.000000      2.000000  2.000000e+03  
25%       22.000000     16.000000    549.000000  2.100000e+04  
50%       26.000000     18.000000   1385.000000  2.999500e+04  
75%       30.000000     22.000000   2009.000000  4.223125e+04  
max      354.000000    137.000000   5657.000000  2.065902e+06

#### Question 2: Number of Records in the dataset: **11914**


In [4]:
def grab_col_names(dataframe):
    cat_cols = [col for col in dataframe.columns if dataframe[col].dtypes == "O"]
    num_cols = [col for col in dataframe.columns if dataframe[col].dtypes != "O"]

    return cat_cols, num_cols

category_column, numeric_column = grab_col_names(df)

In [5]:
print(f"Column with format category or object: {category_column}")
print(f"Column with format integer or float: {numeric_column}")

Column with format category or object: ['Make', 'Model', 'Engine Fuel Type', 'Transmission Type', 'Driven_Wheels', 'Market Category', 'Vehicle Size', 'Vehicle Style']
Column with format integer or float: ['Year', 'Engine HP', 'Engine Cylinders', 'Number of Doors', 'highway MPG', 'city mpg', 'Popularity', 'MSRP']


In [6]:
df[['Year', 'Engine HP', 'Engine Cylinders', 'Number of Doors', 'highway MPG', 'city mpg', 'Popularity', 'MSRP']].dtypes

Year                  int64
Engine HP           float64
Engine Cylinders    float64
Number of Doors     float64
highway MPG           int64
city mpg              int64
Popularity            int64
MSRP                  int64
dtype: object

In [7]:
int_column = [col for col in numeric_column if df[col].dtypes != "int64"]
float_column = [col for col in numeric_column if df[col].dtypes != "float64"]

print(f"Column with format integer: {int_column}")
print(f"Column with format float: {float_column}")

Column with format integer: ['Engine HP', 'Engine Cylinders', 'Number of Doors']
Column with format float: ['Year', 'highway MPG', 'city mpg', 'Popularity', 'MSRP']


In [ ]:
df[int_column] = df[int_column].astype("int16")
df[float_column] = df[float_column].astype("float16")

#### Question 3

The most frequent car manufacturers (top-3) according to the dataset? **Chevrolet, Ford, Volkswagen**


In [8]:
dict_make = dict(df['Make'].value_counts())
dict(list(dict_make.items())[:3])

{'Chevrolet': 1123, 'Ford': 881, 'Volkswagen': 809}

In [9]:
df_audi = df[df['Make'] == 'Audi']
df_audi.head()

Make Model  Year  Engine Fuel Type  Engine HP  Engine Cylinders  \
17  Audi   100  1992  regular unleaded      172.0               6.0   
18  Audi   100  1992  regular unleaded      172.0               6.0   
19  Audi   100  1992  regular unleaded      172.0               6.0   
20  Audi   100  1992  regular unleaded      172.0               6.0   
21  Audi   100  1992  regular unleaded      172.0               6.0   

   Transmission Type      Driven_Wheels  Number of Doors Market Category  \
17            MANUAL  front wheel drive              4.0          Luxury   
18            MANUAL  front wheel drive              4.0          Luxury   
19         AUTOMATIC    all wheel drive              4.0          Luxury   
20            MANUAL  front wheel drive              4.0          Luxury   
21            MANUAL    all wheel drive              4.0          Luxury   

   Vehicle Size Vehicle Style  highway MPG  city mpg  Popularity  MSRP  
17      Midsize         Sedan           24        17        3105  2000  
18      Midsize         Sedan           24        17        3105  2000  
19      Midsize         Wagon           20        16        3105  2000  
20      Midsize         Sedan           24        17        3105  2000  
21      Midsize         Sedan           21        16        3105  2000

In [10]:
df_audi['Model'].unique()

array(['100', '200', '80', '90', 'A3', 'A4 allroad', 'A4', 'A5', 'A6',
       'A7', 'A8', 'allroad quattro', 'allroad', 'Cabriolet', 'Coupe',
       'Q3', 'Q5', 'Q7', 'R8', 'RS 4', 'RS 5', 'RS 6', 'RS 7', 'S3', 'S4',
       'S5', 'S6', 'S7', 'S8', 'SQ5', 'TT RS', 'TT', 'TTS', 'V8'],
      dtype=object)

In [11]:
len(df_audi['Model'].unique())

34

#### Question 4

What's the number of unique Audi car models in the dataset? **34**

In [12]:
df.columns[df.isnull().any()]

Index(['Engine Fuel Type', 'Engine HP', 'Engine Cylinders', 'Number of Doors',
       'Market Category'],
      dtype='object')

In [13]:
len(df.columns[df.isnull().any()])

5

#### Question 5

How many columns in the dataset have missing values? **5**

In [14]:
median_value = df['Engine Cylinders'].quantile(0.5)
median_value

6.0

In [15]:
dict_cylinder = dict(df['Engine Cylinders'].value_counts())
dict(list(dict_cylinder.items())[:1])

{4.0: 4752}

In [16]:
print(f"Total missing values on column 'Engine Cylinders' is {df['Engine Cylinders'].isna().sum()}")

Total missing values on column 'Engine Cylinders' is 30


In [17]:
df['Engine Cylinders'] = df['Engine Cylinders'].fillna(4.0)
dict_cylinder = dict(df['Engine Cylinders'].value_counts())
dict(list(dict_cylinder.items())[:1])

{4.0: 4782}

In [18]:
print(f"Total missing values on column 'Engine Cylinders' after filling with most frequent value is {df['Engine Cylinders'].isna().sum()}")

Total missing values on column 'Engine Cylinders' after filling with most frequent value is 0


In [19]:
median_value_after_filling = df['Engine Cylinders'].quantile(0.5)
median_value_after_filling != median_value

False

#### Question 6 
Has the median value of column 'Engine Cylinder' changed after filling missing values with the most frequent value? **No**


#### Question 7 
What's the value of the first element of w?

In [20]:
## Select all the "Lotus" cars
df_lotus = df[df["Make"] == "Lotus"]
df_lotus.head()

Make  Model  Year             Engine Fuel Type  Engine HP  \
3912  Lotus  Elise  2009  premium unleaded (required)      189.0   
3913  Lotus  Elise  2009  premium unleaded (required)      218.0   
3914  Lotus  Elise  2009  premium unleaded (required)      189.0   
3915  Lotus  Elise  2010  premium unleaded (required)      189.0   
3916  Lotus  Elise  2010  premium unleaded (required)      218.0   

      Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
3912               4.0            MANUAL  rear wheel drive              2.0   
3913               4.0            MANUAL  rear wheel drive              2.0   
3914               4.0            MANUAL  rear wheel drive              2.0   
3915               4.0            MANUAL  rear wheel drive              2.0   
3916               4.0            MANUAL  rear wheel drive              2.0   

              Market Category Vehicle Size Vehicle Style  highway MPG  \
3912  Exotic,High-Performance      Compact   Convertible           27   
3913  Exotic,High-Performance      Compact   Convertible           26   
3914  Exotic,High-Performance      Compact   Convertible           27   
3915  Exotic,High-Performance      Compact   Convertible           27   
3916  Exotic,High-Performance      Compact   Convertible           26   

      city mpg  Popularity   MSRP  
3912        21         613  43995  
3913        20         613  54990  
3914        21         613  47250  
3915        21         613  47250  
3916        20         613  54990

In [21]:
## Select only columns "Engine HP", "Engine Cylinders".
df_lotus_trimmed = df_lotus[["Engine HP", "Engine Cylinders"]]

## Drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
df_lotus_trimmed = df_lotus_trimmed.drop_duplicates()

In [22]:
df_lotus_trimmed

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [23]:
from numpy.linalg import inv

## Get the underlying NumPy array. Let's call it X.
X = np.array(df_lotus_trimmed)
    
## Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX = np.dot(np.transpose(X), X)
    
## Compute the inverse of XTX.
XTX_inverse = inv(XTX) 

In [25]:
print("Matrix X")
print(X)
print("Matrix-matrix multiplication")
print(XTX)
print("Inverse matrix of XTX")
print(XTX_inverse)

Matrix X
[[189.   4.]
 [218.   4.]
 [217.   4.]
 [350.   8.]
 [400.   6.]
 [276.   6.]
 [345.   6.]
 [257.   4.]
 [240.   4.]]
Matrix-matrix multiplication
[[7.31684e+05 1.34100e+04]
 [1.34100e+04 2.52000e+02]]
Inverse matrix of XTX
[[ 5.53084235e-05 -2.94319825e-03]
 [-2.94319825e-03  1.60588447e-01]]


In [26]:
## Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
    
## Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = np.dot(np.dot(XTX_inverse, np.transpose(X)), y)
    
## What's the value of the first element of w?
w[0]

4.594944810094551

#### Answer: The first element of w is 4.594944810094551